import "./globals.css";
import React from "react";

import { LayoutProvider } from "./path.js";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return <LayoutProvider>{children}</LayoutProvider>;
}
